### ISSUE TITLE
..

### ISSUE THREAD

**Issue by mdsiaofficial** [reduan-masud/class-5th-sem#1]
..

**Comment by reduanmasud** [comment]
Hello, Ashiq,
How are you? Currently, I do not have any WhatsApp ID. But you can directly
call me any time
01752883928

**Comment by mdsiaofficial** [comment]
GitHub e msg er system thakle joss hoito... Btw ami apnake LinkedIn e connect korte partesi na.

**Comment by reduanmasud** [comment]
https://www.linkedin.com/in/reduan-masud/

**Comment by mdsiaofficial** [comment]
Hocche na connect. 
linkedin.com/in/mdsiaofficial/

Kindly apni pathay den. Ami dite partesi na!

[Screenshot_2024-04-12-22-04-20-769_com.linkedin.android-edit.jpg](https://github.com/reduanmasud/class-5th-sem/assets/22385106/965a5c1a-16b4-4bff-89ad-3e30c50912b9)

**Comment by mdsiaofficial** [comment]
Hocche na connect. 
https://www.linkedin.com/in/mdsiaofficial/

Kindly apni pathay den. Ami dite partesi na!

[Screenshot_2024-04-12-22-04-20-769_com.linkedin.android-edit.jpg](https://github.com/reduanmasud/class-5th-sem/assets/22385106/965a5c1a-16b4-4bff-89ad-3e30c50912b9)
